- get_url: url=https://oss-binaries.phusionpassenger.com/yum/definitions/el-passenger.repo
           dest=/etc/yum.repos.d/passenger.repo
  sudo: yes
- rpm_key: key=https://packagecloud.io/gpg.key
  sudo: yes

# this makecache is mostly because I can not find any other way to fully
# import the GPG. key for the Passenger repo. 'rpm --import' is not
# sufficient.
- command: yum -q makecache -y --disablerepo='*' --enablerepo='passenger*'
  sudo: yes
  changed_when: False

- yum: name=epel-release
  sudo: yes

- name: install nginx, passenger
  yum: name='{{ item }}'
  sudo: yes
  with_items:
    - nginx
    - passenger

- template: dest=/etc/nginx/conf.d/devmine.conf
            src=devmine.conf.j2
  sudo: yes
  notify: restart nginx

- template: dest=/etc/nginx/conf.d/passenger.conf
            src=passenger.conf.j2
  sudo: yes
  notify: restart nginx

- service: name=nginx
           enabled=yes
           state=running
  sudo: yes
