- name: install EPEL yum repo
  yum: name=epel-release
  sudo: yes

- name: install redmine rpm package
  yum: name='{{ item }}'
  with_items:
    - 'redmine-{{ redmine_version }}'
  sudo: yes

- stat: path='{{ redmine_root_dir }}'
  register: redmine_root_dir_stat

- name: delete contents of redmine root directory
  file: path='{{ redmine_root_dir }}'
        state=absent
  sudo: yes
  register: redmine_root_deleted
  when: redmine_root_dir_stat.stat.exists == True and redmine_db_created|changed

# To generate an archive do:
#   ssh root@<PROD SERVER> '(cd /usr/local; tar zcvf - redmine-2.3.2)' > scratch/redmine-2.3.2.tar.gz
- name: unpack archive copy of production Redmine
  unarchive: src='{{ cache_dir }}/redmine-{{ redmine_version }}.tar.gz'
             dest='/usr/local/'
             copy=no
  sudo: yes
  when: redmine_root_dir_stat.stat.exists == False or redmine_root_deleted|changed

- name: symlink redmine directory
  file: src='{{ redmine_root_dir }}'
        dest=/usr/local/redmine
        state=link
  sudo: yes

- name: configure Redmine database
  template: dest='{{ redmine_root_dir }}/config/database.yml'
            src=templates/redmine_database_config.j2
  sudo: yes

